### ISSUE TITLE
IDEA

### ISSUE THREAD

**Issue by achave11** [faviotorres/Baika#3]
I think your `.idea/` folder should not be there. Since, sensitive information can be pulled out from there. Try using `.gitignore` in the home folder and add all the files and directories that are not required to sustain stable versioning of your code.

Best,

Security For My friends _RM_!

**Comment by faviotorres** [comment]
The files are already tracked and there is history about those files. Android Studio provides a default .gitignore file and it seems like the two most important files in the .idea directory are ignored. I will take this into consideration next time.

Thanks.
